import Head from "next/head";
import Image from "next/image";
import { GraphQLClient, gql } from "graphql-request";
import HeroBanner from "../components/HeroBanner.js";
import BlogCard from "../components/BlogCard.js";
import styles from "../styles/Home.module.css";

const GRAPHCMS = new GraphQLClient(
  "https://api-ap-northeast-1.graphcms.com/v2/cl50mrjcv10n601um2ytwbzlg/master"
);

const HERO_BANNER_IMAGE_QUERY = gql`
  {
    heroBanners {
      heroBannerImage {
        url
      }
    }
  }
`;

const POSTS_QUERY = gql`
  {
    posts {
      id
      coverPhoto {
        publishedAt
        createdBy {
          id
        }
        url
      }
      title
      content {
        html
      }
      author {
        name
        avatar {
          url
        }
      }
      datePublished
      slug
    }
  }
`;

export async function getStaticProps() {
  const { heroBanners } = await GRAPHCMS.request(HERO_BANNER_IMAGE_QUERY);
  const { posts } = await GRAPHCMS.request(POSTS_QUERY);
  return {
    props: {
      heroBanners,
      posts,
    },
    revalidate: 10,
  };
}

const Home = ({ heroBanners, posts }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.heroBanner}>
        {heroBanners.map((heroBanner) => (
          <HeroBanner key="KEY" heroBannerImage={heroBanner.heroBannerImage} />
        ))}
      </div>

      <main className={styles.main}>
        {posts.map((post) => (
          <BlogCard
            key={post.id}
            coverPhoto={post.coverPhoto}
            title={post.title}
            content={post.content}
            author={post.author}
            datePublished={post.datePublished}
            slug={post.slug}
          />
        ))}
      </main>
    </div>
  );
};

export default Home;
